### ISSUE TITLE
调试报错

### ISSUE THREAD

**Issue by spancechou** [ant-design-blazor/ant-design-pro-blazor#44] opened 2020-11-26 11:25 UTC
![image](https://user-images.githubusercontent.com/52477178/100345243-ff936780-301c-11eb-8cf6-9fe651e01b6f.png)
visual studio 开发，调试打开没多久就报错

**Comment by yoli799480165** [comment] 2020-11-27 01:22
Duplicate of #37

**Closed** 2020-11-27 05:17 UTC
